### ISSUE TITLE
无法使用了

### ISSUE THREAD

**Issue by YiChen-X** [kuilei0926/xixunyun#10]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2

无法使用了

**Comment by YiChen-X** [comment]
http://xxy.kuileii.com/release/xixunyun

**Comment by YiChen-X** [comment]
http://xxy.kuileii.com/release/xixunyun无法访问 无法获取data  导致无法使用

**Comment by YiChen-X** [comment]
cd ~/xixunyun
  python xixunyun.py
  shell: /usr/bin/bash -e {0}
  env:
    USER: ***
    SIGN_GPS: ***
    ADDRESS_NAME: ***
    SCKEY: ***
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/YiChen-X/xixunyun/actions/runs/3506175227/jobs/5873033273#step:5:3).8.1[4](https://github.com/YiChen-X/xixunyun/actions/runs/3506175227/jobs/5873033273#step:5:4)/x[6](https://github.com/YiChen-X/xixunyun/actions/runs/3506175227/jobs/5873033273#step:5:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[8](https://github.com/YiChen-X/xixunyun/actions/runs/3506175227/jobs/5873033273#step:5:8).[14](https://github.com/YiChen-X/xixunyun/actions/runs/3506175227/jobs/5873033273#step:5:15)/x64/lib
Traceback (most recent call last):
  File "xixunyun.py", line 24, in <module>
    print(response.json()["data"])
KeyError: 'data'

**Comment by tmyovo** [comment]
+1  我也用不了了   Run cd ~/xixunyun
Traceback (most recent call last):
  File "xixunyun.py", line 24, in <module>
    print(response.json()["data"])
KeyError: 'data'
Error: Process completed with exit code 1.
